In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('train.csv')

In [4]:
df.shape

(20800, 5)

In [5]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


### hence we can see the missing value so we are going to remove those data containing missing value

In [7]:
df = df.dropna()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18285 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      18285 non-null  int64 
 1   title   18285 non-null  object
 2   author  18285 non-null  object
 3   text    18285 non-null  object
 4   label   18285 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 857.1+ KB


### now missing data issue has been solved

## As we can see that title auther and text have text data so we are combining them into a new column name total

In [9]:
df['total'] = df['title']+df['author']+ df['text']

In [10]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  \
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1   
1  Ever get the feeling your life circles the rou...      0   
2  Why the Truth Might Get You Fired October 29, ...      1   
3  Videos 15 Civilians Killed In Single US Airstr...      1   
4  Print \nAn Iranian woman has been sentenced to...      1   

                                               total  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  FLYNN: Hillary Clinton, Big Woman on Campus - ...  
2  Why the Truth Might Get You FiredConsortiumnew...  
3  15 Civilians Killed In Single US Airstrike Hav...  
4  Iranian woman jailed for fictional unpublished...

In [11]:
df.reset_index(inplace = True)

In [12]:
df.head()

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   

               author                                               text  \
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...   
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...   
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...   
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...   
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...   

   label                                              total  
0      1  House Dem Aide: We Didn’t Even See Comey’s Let...  
1      0  FLYNN: Hillary Clinton, Big Woman on Campus - ...  
2      1  Why the Truth Might Get You FiredConsortiumnew...  
3      1  15 Civilians Killed In Single US Airstrike Hav...  
4      1  Iranian woman jailed for fictional unpublished...

In [13]:
df.drop(['id'],axis = 1, inplace = True)

In [14]:
df.head()

index                                              title  \
0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2                  Why the Truth Might Get You Fired   
3      3  15 Civilians Killed In Single US Airstrike Hav...   
4      4  Iranian woman jailed for fictional unpublished...   

               author                                               text  \
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...   
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...   
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...   
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...   
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...   

   label                                              total  
0      1  House Dem Aide: We Didn’t Even See Comey’s Let...  
1      0  FLYNN: Hillary Clinton, Big Woman on Campus - ...  
2      1  Why the Truth Might Get You FiredConsortiumnew...  
3      1  15 Civilians Killed In Single US Airstrike Hav...  
4      1  Iranian woman jailed for fictional unpublished...

## removing stopwords from total and lemmatizing them

In [15]:
import re
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

In [16]:
from nltk.stem import WordNetLemmatizer
lt = WordNetLemmatizer()

In [17]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [18]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Ashish\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [19]:
df.head()

index                                              title  \
0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2                  Why the Truth Might Get You Fired   
3      3  15 Civilians Killed In Single US Airstrike Hav...   
4      4  Iranian woman jailed for fictional unpublished...   

               author                                               text  \
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...   
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...   
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...   
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...   
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...   

   label                                              total  
0      1  House Dem Aide: We Didn’t Even See Comey’s Let...  
1      0  FLYNN: Hillary Clinton, Big Woman on Campus - ...  
2      1  Why the Truth Might Get You FiredConsortiumnew...  
3      1  15 Civilians Killed In Single US Airstrike Hav...  
4      1  Iranian woman jailed for fictional unpublished...

In [20]:
x = df.drop(['index','title','author','text','label'],axis = 1)

In [21]:
x.head()

total
0  House Dem Aide: We Didn’t Even See Comey’s Let...
1  FLYNN: Hillary Clinton, Big Woman on Campus - ...
2  Why the Truth Might Get You FiredConsortiumnew...
3  15 Civilians Killed In Single US Airstrike Hav...
4  Iranian woman jailed for fictional unpublished...

In [22]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Ashish\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [23]:
for index,row in x.iterrows():
    sentence = row['total']
    sentence = re.sub(r'[^\w\s]'," ",sentence)
    x.loc[index,'total'] = sentence

In [24]:
for index,row in x.iterrows():
    sentence = row['total']
    x.loc[index,'total'] = sentence.lower()

In [25]:
x.head(100)

total
0   house dem aide  we didn t even see comey s let...
1   flynn  hillary clinton  big woman on campus   ...
2   why the truth might get you firedconsortiumnew...
3   15 civilians killed in single us airstrike hav...
4   iranian woman jailed for fictional unpublished...
..                                                ...
95  ncaa  big 12 keeps watchful eye on texas bathr...
96  massive espn financial  subscriber losses drag...
97  megyn kelly  contract set to expire next year ...
98  teacher suspended for allowing students to hit...
99  breaking   trump expressed concern over anthon...

[100 rows x 1 columns]

In [26]:
a = 'been had done language cities mice'
h = a.split()
b = ""
h = [w for w in h if not w in stop_words]
for word in h:
   b = b + " " + lt.lemmatize(word)
print(b)

 done language city mouse


In [27]:
corpus = []
for index,row in x.iterrows():
    filter_sentence = ""
    sentence = row['total']
    words = sentence.split()
    
    words = [w for w in words if not w in stop_words]
    
    for word in words:
        filter_sentence = filter_sentence + " " +lt.lemmatize(word)
        
    corpus.append(filter_sentence)

In [ ]:
corpus

## now lemmatizing and stopwords has been removed 

## now we are applying bag of words using count vectorizer

## in this each word is reresented by a vector, in bad of words it is represented by the position of the word and in count vectorizer it is by the frequency of the word

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

In [31]:
Corpus = ['this is the first document',
            'this document is the second document',
          'and this is the third one',
         'is this the fourth document']
vt = CountVectorizer()
X = vt.fit_transform(Corpus)
print(vt.get_feature_names())

['and', 'document', 'first', 'fourth', 'is', 'one', 'second', 'the', 'third', 'this']


In [32]:
type(X)

scipy.sparse.csr.csr_matrix

In [33]:
print(X)

  (0, 9)	1
  (0, 4)	1
  (0, 7)	1
  (0, 2)	1
  (0, 1)	1
  (1, 9)	1
  (1, 4)	1
  (1, 7)	1
  (1, 1)	2
  (1, 6)	1
  (2, 9)	1
  (2, 4)	1
  (2, 7)	1
  (2, 0)	1
  (2, 8)	1
  (2, 5)	1
  (3, 9)	1
  (3, 4)	1
  (3, 7)	1
  (3, 1)	1
  (3, 3)	1


In [34]:
count_df = pd.DataFrame(X, columns = vt.get_feature_names())

ValueError: Shape of passed values is (4, 1), indices imply (4, 10)

In [35]:
count_df.head()

NameError: name 'count_df' is not defined

In [36]:
x = x['total']

In [37]:
x.head()

0    house dem aide  we didn t even see comey s let...
1    flynn  hillary clinton  big woman on campus   ...
2    why the truth might get you firedconsortiumnew...
3    15 civilians killed in single us airstrike hav...
4    iranian woman jailed for fictional unpublished...
Name: total, dtype: object

In [38]:
c = CountVectorizer(max_features = 1000)
freq_term_matrix = c.fit_transform(corpus).toarray()
# freq_term_matrix = count_vectorizer.transform(x)

In [39]:
freq_term_matrix.shape

(18285, 1000)

In [40]:
print(freq_term_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 2 0 0]
 ...
 [1 1 0 ... 0 1 0]
 [0 1 0 ... 0 0 0]
 [3 0 0 ... 0 0 0]]


In [41]:
a = c.get_feature_names()

In [42]:
a[999]

'young'

In [43]:
x_train = pd.DataFrame(freq_term_matrix, columns = a)

In [44]:
x_train.head(100)

000  10  100  11  12  15  16  18  20  2012  ...  working  world  would  \
0     0   0    0   0   0   0   0   0   0     1  ...        0      3      0   
1     0   0    0   0   0   0   0   0   0     0  ...        0      0      0   
2     0   0    0   1   0   0   1   0   0     0  ...        0      1      1   
3     0   0    0   0   0   5   0   1   0     0  ...        0      0      0   
4     0   0    0   0   0   0   0   0   0     0  ...        0      0      0   
..  ...  ..  ...  ..  ..  ..  ..  ..  ..   ...  ...      ...    ...    ...   
95    0   0    0   0   6   0   0   0   0     0  ...        0      0      0   
96    0   0    1   1   0   0   0   0   0     0  ...        0      0      2   
97    0   0    1   0   0   0   0   0   1     0  ...        0      0      7   
98    0   0    0   0   0   0   0   0   0     0  ...        0      0      1   
99    0   0    0   0   0   0   0   0   0     0  ...        0      0      0   

    wrong  wrote  year  yes  yet  york  young  
0       0      0     2    0    0     0      0  
1       0      0     1    0    0     0      0  
2       0      0     1    0    2     0      0  
3       0      0     0    0    0     0      0  
4       0      0     2    0    0     0      0  
..    ...    ...   ...  ...  ...   ...    ...  
95      0      1     1    0    0     0      0  
96      0      1     5    0    0     0      0  
97      0      0     8    0    0     1      0  
98      0      0     0    0    1     0      0  
99      0      0     0    0    0     0      0  

[100 rows x 1000 columns]

In [45]:
df.head()

index                                              title  \
0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2                  Why the Truth Might Get You Fired   
3      3  15 Civilians Killed In Single US Airstrike Hav...   
4      4  Iranian woman jailed for fictional unpublished...   

               author                                               text  \
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...   
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...   
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...   
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...   
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...   

   label                                              total  
0      1  House Dem Aide: We Didn’t Even See Comey’s Let...  
1      0  FLYNN: Hillary Clinton, Big Woman on Campus - ...  
2      1  Why the Truth Might Get You FiredConsortiumnew...  
3      1  15 Civilians Killed In Single US Airstrike Hav...  
4      1  Iranian woman jailed for fictional unpublished...

In [46]:
y_train = df['label']

In [47]:
y_train.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [48]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x_train,y_train,random_state = 42)

In [49]:
print(X_train.shape,Y_train.shape)

(13713, 1000) (13713,)


In [50]:
print(X_test.shape,Y_test.shape)

(4572, 1000) (4572,)


In [51]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(C = 1e5,max_iter = 1000)
model.fit(X_train,Y_train)

LogisticRegression(C=100000.0, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=1000, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [52]:
pred = model.predict(X_test)

In [53]:
Y_test.shape

(4572,)

In [54]:
type(pred)

numpy.ndarray

In [55]:
pred.shape

(4572,)

In [57]:
model.score(X_test,pred)

1.0

In [110]:
test = pd.read_csv('test.csv')

In [111]:
test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [112]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      5200 non-null   int64 
 1   title   5078 non-null   object
 2   author  4697 non-null   object
 3   text    5193 non-null   object
dtypes: int64(1), object(3)
memory usage: 162.6+ KB


In [61]:
test = test.dropna()

In [62]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4575 entries, 0 to 5199
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      4575 non-null   int64 
 1   title   4575 non-null   object
 2   author  4575 non-null   object
 3   text    4575 non-null   object
dtypes: int64(1), object(3)
memory usage: 178.7+ KB


In [122]:
test['text'] = test['text'].replace(np.nan, test['title'])
test['title'] = test['title'].replace(np.nan, test['text'])
test['author'] = test['author'].replace(np.nan, " ")
test.isnull().sum()

id          0
title       0
author      0
text        0
total     503
dtype: int64

In [119]:
test['author'].fillna(" ")

0              David Streitfeld
1                              
2                 Common Dreams
3                 Daniel Victor
4       Truth Broadcast Network
                 ...           
5195                 Jody Rosen
5196        Sheryl Gay Stolberg
5197               Mike McPhate
5198                           
5199                Teddy Wayne
Name: author, Length: 5200, dtype: object

In [123]:
test['total']= test['title'] + test['author'] + test['text']

In [124]:
test['total'].fillna(test['title']+test['text'])

0       Specter of Trump Loosens Tongues, if Not Purse...
1       Russian warships ready to strike terrorists ne...
2       #NoDAPL: Native American Leaders Vow to Stay A...
3       Tim Tebow Will Attempt Another Comeback, This ...
4       Keiser Report: Meme Wars (E995)Truth Broadcast...
                              ...                        
5195    The Bangladeshi Traffic Jam That Never Ends - ...
5196    John Kasich Signs One Abortion Bill in Ohio bu...
5197    California Today: What, Exactly, Is in Your Su...
5198    300 US Marines To Be Deployed To Russian Borde...
5199    Awkward Sex, Onscreen and Off - The New York T...
Name: total, Length: 5200, dtype: object

In [125]:
test.isnull().sum()

id        0
title     0
author    0
text      0
total     0
dtype: int64

In [126]:
test.reset_index(inplace = True)

In [127]:
test.head(10)

index     id                                              title  \
0      0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1      1  20801  Russian warships ready to strike terrorists ne...   
2      2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3      3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4      4  20804                    Keiser Report: Meme Wars (E995)   
5      5  20805  Trump is USA's antique hero. Clinton will be n...   
6      6  20806  Pelosi Calls for FBI Investigation to Find Out...   
7      7  20807            Weekly Featured Profile – Randy Shannon   
8      8  20808  Urban Population Booms Will Make Climate Chang...   
9      9  20809                         don't we have the receipt?   

                    author                                               text  \
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...   
1                           Russian warships ready to strike terrorists ne...   
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...   
3            Daniel Victor  If at first you don’t succeed, try a different...   
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...   
5                           Trump is USA's antique hero. Clinton will be n...   
6                  Pam Key  Sunday on NBC’s “Meet the Press,” House Minori...   
7            Trevor Loudon  You are here: Home / *Articles of the Bound* /...   
8                           Urban Population Booms Will Make Climate Chang...   
9      cognitive dissident                         don't we have the receipt?   

                                               total  
0  Specter of Trump Loosens Tongues, if Not Purse...  
1  Russian warships ready to strike terrorists ne...  
2  #NoDAPL: Native American Leaders Vow to Stay A...  
3  Tim Tebow Will Attempt Another Comeback, This ...  
4  Keiser Report: Meme Wars (E995)Truth Broadcast...  
5  Trump is USA's antique hero. Clinton will be n...  
6  Pelosi Calls for FBI Investigation to Find Out...  
7  Weekly Featured Profile – Randy ShannonTrevor ...  
8  Urban Population Booms Will Make Climate Chang...  
9  don't we have the receipt?cognitive dissidentd...

In [128]:
tx = test.drop(['id','title','author','text','index'],axis = 1)

In [129]:
tx.head()

total
0  Specter of Trump Loosens Tongues, if Not Purse...
1  Russian warships ready to strike terrorists ne...
2  #NoDAPL: Native American Leaders Vow to Stay A...
3  Tim Tebow Will Attempt Another Comeback, This ...
4  Keiser Report: Meme Wars (E995)Truth Broadcast...

In [130]:
for i,r in tx.iterrows():
    sentence = r['total']
    sentence = re.sub(r'[^\w\s]'," ",sentence)
    tx.loc[i,'total'] = sentence

In [131]:
for i,r in tx.iterrows():
    sentence = r['total']
    tx.loc[i,'total'] = sentence.lower()

In [132]:
Corpus = []
for i,r in tx.iterrows():
    filter_sentence = ""
    sentence = r['total']
    Words = sentence.split()
    
    Words = [w for w in Words if not w in stop_words]
    
    for Word in Words:
        filter_sentence = filter_sentence + " " +lt.lemmatize(Word)
        
    Corpus.append(filter_sentence)

In [133]:
Corpus

[' specter trump loosens tongue purse string silicon valley new york timesdavid streitfeldpalo alto calif year scorning political process silicon valley leapt fray prospect president donald j trump pushing tech community move beyond traditional role donor embrace new existence agitator activist distinguished venture capital firm emblazoned corporate home page earthy epithet one prominent tech chieftain say consequence mr trump election would range disastrous terrible another compare dictator nearly 150 tech leader signed open letter decrying mr trump campaign anger bigotry quite action peter thiel founder paypal palantir first outside investor facebook spoke republican convention july new york time reported saturday mr thiel giving 1 25 million support mr trump candidacy even supporter flee also recently gave 1 million super pac support senator rob portman republican freshman running ohio getting involved politics used seen clashing silicon valley value system transform world making pr

In [134]:
C = CountVectorizer(max_features = 1000)
freq_matrix = C.fit_transform(Corpus).toarray()

In [135]:
A = C.get_feature_names()

In [136]:
A

['000',
 '10',
 '100',
 '11',
 '12',
 '14',
 '15',
 '16',
 '18',
 '20',
 '2008',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '25',
 '26',
 '27',
 '30',
 '40',
 '50',
 'ability',
 'able',
 'access',
 'according',
 'account',
 'accused',
 'across',
 'act',
 'action',
 'activist',
 'activity',
 'actually',
 'added',
 'adding',
 'address',
 'administration',
 'adviser',
 'age',
 'agency',
 'agent',
 'ago',
 'agreement',
 'aide',
 'air',
 'al',
 'allow',
 'allowed',
 'ally',
 'almost',
 'along',
 'already',
 'also',
 'although',
 'always',
 'america',
 'american',
 'among',
 'amount',
 'analyst',
 'announced',
 'another',
 'answer',
 'anti',
 'anyone',
 'anything',
 'appear',
 'appeared',
 'appears',
 'approach',
 'april',
 'area',
 'arm',
 'army',
 'around',
 'art',
 'article',
 'ask',
 'asked',
 'assault',
 'attack',
 'attempt',
 'attention',
 'attorney',
 'audience',
 'author',
 'authority',
 'available',
 'away',
 'back',
 'bad',
 'ballot',
 'ban',
 'bank',
 'barack'

In [137]:
TX = pd.DataFrame(freq_matrix, columns = A)

In [138]:
TX.head()

000  10  100  11  12  14  15  16  18  20  ...  world  would  written  \
0    6   1    0   0   0   0   0   0   0   1  ...      1      4        0   
1    0   0    0   1   0   0   0   0   0   0  ...      0      1        0   
2    0   1    0   0   0   0   0   0   0   0  ...      0      0        1   
3    0   0    0   0   0   0   0   0   0   0  ...      0      3        0   
4    0   0    0   0   0   0   0   0   0   0  ...      0      0        0   

   wrong  wrote  year  yes  yet  york  young  
0      0      1     1    0    1     2      0  
1      0      0     0    0    0     0      0  
2      2      0     0    0    0     0      0  
3      0      0     4    0    0     1      0  
4      0      0     0    0    0     0      0  

[5 rows x 1000 columns]

In [139]:
result = model.predict(TX)

In [140]:
result

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [141]:
id = test['id']

In [142]:
h = pd.DataFrame(result)

In [143]:
final = pd.concat([id,h],axis = 1)

In [144]:
final.to_csv('results.csv',index = False)